import dotenv from 'dotenv';
dotenv.config(); 

export default  {
  MINIO_ENDPOINT: process.env.MINIO_ENDPOINT || 'localhost',
  MINIO_ACCESS_KEY: process.env.MINIO_ACCESS_KEY || 'admin',
  MINIO_SECRET_KEY: process.env.MINIO_SECRET_KEY || 'admin123',
  MINIO_BUCKET: process.env.MINIO_BUCKET || 'DMS-bucket',
  MINIO_PORT: process.env.MINIO_PORT || '9000', 


  S3_ENDPOINT: process.env.S3_ENDPOINT ,
  S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID ,
  S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY ,
  S3_BUCKET: process.env.S3_BUCKET ,

  key: process.env.KEY,
  newKey: process.env.NEW_KEY,
  passwordAccess: process.env.PASSWORD_ACCESS,
  passwordRefresh: process.env.PASSWORD_REFRESH,
  passwordCookie: process.env.PASSWORD_COOKIE,
  createAcctBlocked: process.env.BLOCK_CREATE_ACCOUNT === "true",
  root: process.env.ROOT,
  url: process.env.URL,
  mongoURL: process.env.MONGODB_URL,
  dbType: process.env.DB_TYPE,
  fsDirectory: process.env.FS_DIRECTORY,
  s3ID: process.env.S3_ID,
  s3Key: process.env.S3_KEY,
  s3Bucket: process.env.S3_BUCKET,
  s3Endpoint: process.env.S3_ENDPOINT, 
  useDocumentDB: process.env.USE_DOCUMENT_DB,
  documentDBBundle: process.env.DOCUMENT_DB_BUNDLE,
  sendgridKey: process.env.SENDGRID_KEY,
  sendgridEmail: process.env.SENDGRID_EMAIL,
  remoteURL: process.env.REMOTE_URL,
  secureCookies: process.env.SECURE_COOKIES,
  tempDirectory: process.env.TEMP_DIRECTORY,
  emailVerification: process.env.EMAIL_VERIFICATION,
  emailDomain: process.env.EMAIL_DOMAIN,
  emailAPIKey: process.env.EMAIL_API_KEY,
  emailHost: process.env.EMAIL_HOST,
  emailPort: process.env.EMAIL_PORT,
  emailAddress: process.env.EMAIL_ADDRESS,
  videoThumbnailsEnabled: process.env.VIDEO_THUMBNAILS_ENABLED === "true",
  tempVideoThumbnailLimit: process.env.TEMP_VIDEO_THUMBNAIL_LIMIT
    ? +process.env.TEMP_VIDEO_THUMBNAIL_LIMIT
    : 0,
  docker: process.env.DOCKER === "true",
  httpsKeyPath: process.env.HTTPS_KEY_PATH,
  httpsCaPath: process.env.HTTPS_CA_PATH,
  httpsCrtPath: process.env.HTTPS_CRT_PATH,
};


module.exports = {
  S3_ENDPOINT: process.env.S3_ENDPOINT || 'http://localhost:9000',
  S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID || 'admin',
  S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY || 'admin123',
  S3_BUCKET: process.env.S3_BUCKET || 'dms-bucket',
  key: process.env.KEY,
  newKey: process.env.NEW_KEY,
  passwordAccess: process.env.PASSWORD_ACCESS,
  passwordRefresh: process.env.PASSWORD_REFRESH,
  passwordCookie: process.env.PASSWORD_COOKIE,
  createAcctBlocked: process.env.BLOCK_CREATE_ACCOUNT === "true",
  root: process.env.ROOT,
  url: process.env.URL,
  mongoURL: process.env.MONGODB_URL,
  dbType: process.env.DB_TYPE,
  fsDirectory: process.env.FS_DIRECTORY,
  s3ID: process.env.S3_ID,
  s3Key: process.env.S3_KEY,
  s3Bucket: process.env.S3_BUCKET,
  s3Endpoint: process.env.S3_ENDPOINT, 
  useDocumentDB: process.env.USE_DOCUMENT_DB,
  documentDBBundle: process.env.DOCUMENT_DB_BUNDLE,
  sendgridKey: process.env.SENDGRID_KEY,
  sendgridEmail: process.env.SENDGRID_EMAIL,
  remoteURL: process.env.REMOTE_URL,
  secureCookies: process.env.SECURE_COOKIES,
  tempDirectory: process.env.TEMP_DIRECTORY,
  emailVerification: process.env.EMAIL_VERIFICATION,
  emailDomain: process.env.EMAIL_DOMAIN,
  emailAPIKey: process.env.EMAIL_API_KEY,
  emailHost: process.env.EMAIL_HOST,
  emailPort: process.env.EMAIL_PORT,
  emailAddress: process.env.EMAIL_ADDRESS,
  videoThumbnailsEnabled: process.env.VIDEO_THUMBNAILS_ENABLED === "true",
  tempVideoThumbnailLimit: process.env.TEMP_VIDEO_THUMBNAIL_LIMIT
    ? +process.env.TEMP_VIDEO_THUMBNAIL_LIMIT
    : 0,
  docker: process.env.DOCKER === "true",
  httpsKeyPath: process.env.HTTPS_KEY_PATH,
  httpsCaPath: process.env.HTTPS_CA_PATH,
  httpsCrtPath: process.env.HTTPS_CRT_PATH,
};
